import type {
  AccountSummary,
  ActivityItem,
  MovementRecord,
  NotificationItem,
  ObligationSummary,
  SubscriptionSummary,
  UserProfile,
  Workspace,
} from "../types/domain";

export const mockUser: UserProfile = {
  id: "9ff8fbc0-3ef8-410e-90d6-5d0f16b9cd23",
  fullName: "Lucia Ramirez",
  email: "lucia@darkmoney.app",
  initials: "LR",
  baseCurrencyCode: "USD",
  timezone: "America/Lima",
};

export const mockWorkspaces: Workspace[] = [
  {
    id: 101,
    name: "Lucia Personal",
    kind: "personal",
    role: "owner",
    description: "Finanzas personales y cuentas individuales.",
    baseCurrencyCode: "USD",
  },
  {
    id: 202,
    name: "Casa Ramirez",
    kind: "shared",
    role: "admin",
    description: "Gastos compartidos de pareja y hogar.",
    baseCurrencyCode: "USD",
  },
];

export const mockAccounts: AccountSummary[] = [
  {
    id: 1,
    workspaceId: 101,
    name: "Billetera diaria",
    type: "cash",
    currencyCode: "USD",
    openingBalance: 420,
    currentBalance: 860,
    currentBalanceInBaseCurrency: 860,
    includeInNetWorth: true,
    lastActivity: "2026-03-12T16:15:00.000Z",
    color: "#1e5f52",
    icon: "wallet",
    isArchived: false,
  },
  {
    id: 2,
    workspaceId: 101,
    name: "Cuenta ahorro premium",
    type: "savings",
    currencyCode: "USD",
    openingBalance: 2500,
    currentBalance: 5240,
    currentBalanceInBaseCurrency: 5240,
    includeInNetWorth: true,
    lastActivity: "2026-03-10T09:30:00.000Z",
    color: "#b48b34",
    icon: "piggy-bank",
    isArchived: false,
  },
  {
    id: 3,
    workspaceId: 202,
    name: "Caja del hogar",
    type: "bank",
    currencyCode: "USD",
    openingBalance: 1700,
    currentBalance: 3480,
    currentBalanceInBaseCurrency: 3480,
    includeInNetWorth: true,
    lastActivity: "2026-03-12T19:10:00.000Z",
    color: "#d36c45",
    icon: "home",
    isArchived: false,
  },
  {
    id: 4,
    workspaceId: 202,
    name: "Tarjeta compartida",
    type: "credit_card",
    currencyCode: "USD",
    openingBalance: -420,
    currentBalance: -1180,
    currentBalanceInBaseCurrency: -1180,
    includeInNetWorth: false,
    lastActivity: "2026-03-13T12:20:00.000Z",
    color: "#8f3e3e",
    icon: "credit-card",
    isArchived: false,
  },
];

export const mockMovements: MovementRecord[] = [
  {
    id: 1001,
    workspaceId: 202,
    movementType: "expense",
    status: "posted",
    description: "Supermercado semanal",
    category: "Alimentos",
    counterparty: "Mercado Central",
    occurredAt: "2026-03-13T02:15:00.000Z",
    sourceAccountId: 3,
    sourceAccountName: "Caja del hogar",
    sourceAmount: 126.4,
    destinationAccountId: null,
    destinationAccountName: null,
    destinationAmount: null,
  },
  {
    id: 1002,
    workspaceId: 202,
    movementType: "subscription_payment",
    status: "pending",
    description: "Streaming familiar",
    category: "Suscripciones",
    counterparty: "Stream+",
    occurredAt: "2026-03-14T09:00:00.000Z",
    sourceAccountId: 4,
    sourceAccountName: "Tarjeta compartida",
    sourceAmount: 19.9,
    destinationAccountId: null,
    destinationAccountName: null,
    destinationAmount: null,
  },
  {
    id: 1003,
    workspaceId: 101,
    movementType: "income",
    status: "posted",
    description: "Pago de consultoria",
    category: "Ingresos",
    counterparty: "North Studio",
    occurredAt: "2026-03-11T14:45:00.000Z",
    sourceAccountId: null,
    sourceAccountName: null,
    sourceAmount: null,
    destinationAccountId: 2,
    destinationAccountName: "Cuenta ahorro premium",
    destinationAmount: 950,
  },
  {
    id: 1004,
    workspaceId: 101,
    movementType: "transfer",
    status: "posted",
    description: "Reserva mensual",
    category: "Transferencia",
    counterparty: "Interna",
    occurredAt: "2026-03-09T18:10:00.000Z",
    sourceAccountId: 1,
    sourceAccountName: "Billetera diaria",
    sourceAmount: 180,
    destinationAccountId: 2,
    destinationAccountName: "Cuenta ahorro premium",
    destinationAmount: 180,
  },
];

export const mockObligations: ObligationSummary[] = [
  {
    id: 71,
    workspaceId: 202,
    title: "Laptop del estudio",
    direction: "payable",
    originType: "purchase_financed",
    counterparty: "TechPoint",
    counterpartyId: 9001,
    settlementAccountId: 1,
    settlementAccountName: "Cuenta operativa",
    status: "active",
    currencyCode: "USD",
    principalAmount: 2200,
    principalAmountInBaseCurrency: 2200,
    pendingAmount: 880,
    pendingAmountInBaseCurrency: 880,
    progressPercent: 60,
    startDate: "2025-08-12",
    dueDate: "2026-05-12",
    installmentAmount: 220,
    installmentCount: 10,
    interestRate: 0,
    description: "Compra financiada del equipo principal del estudio.",
    notes: null,
    paymentCount: 6,
    lastPaymentDate: "2026-02-12",
    installmentLabel: "6 de 10 cuotas",
    events: [
      {
        id: 7001,
        eventType: "payment",
        eventDate: "2026-02-12",
        amount: 220,
        installmentNo: 6,
        description: "Pago de cuota febrero",
        notes: null,
        movementId: null,
      },
    ],
  },
  {
    id: 72,
    workspaceId: 101,
    title: "Prestamo a Diego",
    direction: "receivable",
    originType: "cash_loan",
    counterparty: "Diego Salas",
    counterpartyId: 9002,
    settlementAccountId: 3,
    settlementAccountName: "Cuenta principal",
    status: "active",
    currencyCode: "USD",
    principalAmount: 600,
    principalAmountInBaseCurrency: 600,
    pendingAmount: 220,
    pendingAmountInBaseCurrency: 220,
    progressPercent: 63,
    startDate: "2025-12-04",
    dueDate: "2026-04-04",
    installmentAmount: null,
    installmentCount: null,
    interestRate: 0,
    description: "Prestamo personal pactado en pagos flexibles.",
    notes: null,
    paymentCount: 2,
    lastPaymentDate: "2026-02-28",
    installmentLabel: "2 pagos recibidos",
    events: [
      {
        id: 7002,
        eventType: "payment",
        eventDate: "2026-02-28",
        amount: 190,
        installmentNo: null,
        description: "Segundo abono recibido",
        notes: null,
        movementId: null,
      },
    ],
  },
];

export const mockSubscriptions: SubscriptionSummary[] = [
  {
    id: 501,
    workspaceId: 202,
    name: "Internet hogar",
    vendorPartyId: 9101,
    vendor: "FibraX",
    accountId: 1,
    categoryId: 210,
    categoryName: "Servicios",
    status: "active",
    amount: 42,
    amountInBaseCurrency: 42,
    currencyCode: "USD",
    frequency: "monthly",
    frequencyLabel: "monthly",
    intervalCount: 1,
    dayOfMonth: 18,
    dayOfWeek: null,
    startDate: "2025-10-18",
    nextDueDate: "2026-03-18",
    endDate: null,
    remindDaysBefore: 3,
    accountName: "Cuenta operativa",
    autoCreateMovement: false,
    description: "Plan de internet del hogar.",
    notes: null,
  },
  {
    id: 502,
    workspaceId: 202,
    name: "Streaming familiar",
    vendorPartyId: 9102,
    vendor: "Stream+",
    accountId: 1,
    categoryId: 211,
    categoryName: "Suscripciones",
    status: "active",
    amount: 19.9,
    amountInBaseCurrency: 19.9,
    currencyCode: "USD",
    frequency: "monthly",
    frequencyLabel: "monthly",
    intervalCount: 1,
    dayOfMonth: 14,
    dayOfWeek: null,
    startDate: "2025-09-14",
    nextDueDate: "2026-03-14",
    endDate: null,
    remindDaysBefore: 2,
    accountName: "Cuenta operativa",
    autoCreateMovement: true,
    description: "Servicio de streaming compartido.",
    notes: null,
  },
  {
    id: 503,
    workspaceId: 101,
    name: "Suite creativa",
    vendorPartyId: 9103,
    vendor: "Pixel Cloud",
    accountId: 3,
    categoryId: 212,
    categoryName: "Suscripciones",
    status: "paused",
    amount: 28,
    amountInBaseCurrency: 28,
    currencyCode: "USD",
    frequency: "monthly",
    frequencyLabel: "monthly",
    intervalCount: 1,
    dayOfMonth: 21,
    dayOfWeek: null,
    startDate: "2025-11-21",
    nextDueDate: "2026-03-21",
    endDate: null,
    remindDaysBefore: 5,
    accountName: "Cuenta principal",
    autoCreateMovement: false,
    description: "Herramientas creativas del equipo.",
    notes: null,
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 901,
    title: "Movimiento compartido registrado",
    body: "Ana cargo un gasto de supermercado en Caja del hogar.",
    status: "pending",
    scheduledFor: "2026-03-13T02:20:00.000Z",
    kind: "movement",
  },
  {
    id: 902,
    title: "Suscripcion por vencer",
    body: "Streaming familiar vence manana y aun no tiene pago confirmado.",
    status: "sent",
    scheduledFor: "2026-03-13T08:00:00.000Z",
    kind: "subscription",
  },
  {
    id: 903,
    title: "Nuevo rol en workspace",
    body: "Ahora tienes permisos de admin en Casa Ramirez.",
    status: "read",
    scheduledFor: "2026-03-11T10:00:00.000Z",
    kind: "workspace",
  },
];

export const mockActivity: ActivityItem[] = [
  {
    id: 701,
    workspaceId: 202,
    actor: "Ana",
    action: "created",
    entity: "movement",
    description: "Registro el gasto de supermercado en Caja del hogar.",
    createdAt: "2026-03-13T02:15:00.000Z",
  },
  {
    id: 702,
    workspaceId: 202,
    actor: "Lucia",
    action: "updated",
    entity: "account",
    description: "Actualizo el alias visual de Tarjeta compartida.",
    createdAt: "2026-03-12T20:10:00.000Z",
  },
  {
    id: 703,
    workspaceId: 101,
    actor: "Lucia",
    action: "paid",
    entity: "obligation",
    description: "Registro un abono parcial del prestamo a Diego.",
    createdAt: "2026-03-11T19:40:00.000Z",
  },
];

export const mockCashflow = [
  { label: "Oct", income: 2200, expense: 1480 },
  { label: "Nov", income: 2480, expense: 1620 },
  { label: "Dic", income: 2710, expense: 1740 },
  { label: "Ene", income: 2380, expense: 1810 },
  { label: "Feb", income: 2640, expense: 1925 },
  { label: "Mar", income: 2910, expense: 1760 },
];
