create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text null,
  provider_event_type text null,
  user_id uuid null references auth.users(id) on delete set null,
  external_reference text null,
  payload jsonb not null default '{}'::jsonb,
  processed boolean not null default false,
  processing_error text null,
  processed_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint billing_events_provider_chk check (provider in ('mercado_pago', 'lemon_squeezy', 'paddle')),
  constraint billing_events_payload_object_chk check (jsonb_typeof(payload) = 'object')
);

comment on table public.billing_events is
  'Bitacora tecnica de eventos de cobro y webhooks de proveedores externos como Mercado Pago, Lemon Squeezy o Paddle.';

comment on column public.billing_events.provider_event_id is
  'ID externo del evento o recurso enviado por el proveedor.';

comment on column public.billing_events.external_reference is
  'Referencia funcional propia para enlazar el evento con el usuario o flujo interno.';

comment on column public.billing_events.payload is
  'Payload crudo o enriquecido del proveedor para auditoria y troubleshooting.';

drop index if exists public.billing_events_provider_event_unique_idx;
create unique index billing_events_provider_event_unique_idx
  on public.billing_events (provider, provider_event_id);

create index if not exists billing_events_user_created_idx
  on public.billing_events (user_id, created_at desc);

create index if not exists billing_events_provider_created_idx
  on public.billing_events (provider, created_at desc);

alter table public.billing_events enable row level security;

drop policy if exists billing_events_service_role_only on public.billing_events;
create policy billing_events_service_role_only
  on public.billing_events
  for all
  to service_role
  using (true)
  with check (true);

grant all on public.billing_events to service_role;
grant all on sequence public.billing_events_id_seq to service_role;
