create table if not exists public.claim_book_entries (
  id bigint generated by default as identity primary key,
  claim_code text not null unique,
  consumer_name text not null,
  document_type text not null,
  document_number text not null,
  email text not null,
  phone text not null,
  address text not null,
  city text not null,
  asset_type text not null,
  complaint_type text not null,
  order_reference text null,
  amount_claimed numeric(12, 2) null,
  currency_code text null,
  description text not null,
  requested_resolution text not null,
  truth_confirmation boolean not null default false,
  data_processing_confirmation boolean not null default false,
  status text not null default 'received',
  admin_notes text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint claim_book_entries_asset_type_chk
    check (asset_type in ('producto', 'servicio')),
  constraint claim_book_entries_complaint_type_chk
    check (complaint_type in ('reclamo', 'queja')),
  constraint claim_book_entries_status_chk
    check (status in ('received', 'in_review', 'answered', 'closed')),
  constraint claim_book_entries_metadata_object_chk
    check (jsonb_typeof(metadata) = 'object')
);

comment on table public.claim_book_entries is
  'Libro de reclamaciones integrado de DarkMoney para registrar quejas y reclamos desde la web.';

create index if not exists idx_claim_book_entries_created_at
  on public.claim_book_entries(created_at desc);

create index if not exists idx_claim_book_entries_status
  on public.claim_book_entries(status, created_at desc);

create index if not exists idx_claim_book_entries_email
  on public.claim_book_entries(email);

create or replace function public.trg_claim_book_entries_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_claim_book_entries_touch_updated_at on public.claim_book_entries;

create trigger trg_claim_book_entries_touch_updated_at
before update on public.claim_book_entries
for each row
execute function public.trg_claim_book_entries_touch_updated_at();

alter table public.claim_book_entries enable row level security;

drop policy if exists claim_book_entries_public_insert on public.claim_book_entries;
create policy claim_book_entries_public_insert
  on public.claim_book_entries
  for insert
  to anon, authenticated
  with check (
    truth_confirmation = true
    and data_processing_confirmation = true
  );

drop policy if exists claim_book_entries_service_role_all on public.claim_book_entries;
create policy claim_book_entries_service_role_all
  on public.claim_book_entries
  for all
  to service_role
  using (true)
  with check (true);

grant insert on public.claim_book_entries to anon, authenticated;
grant usage, select on sequence public.claim_book_entries_id_seq to anon, authenticated;
grant usage, select on sequence public.claim_book_entries_id_seq to service_role;
grant all on public.claim_book_entries to service_role;
