create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  created_by_user_id uuid null,
  updated_by_user_id uuid null,
  name text not null,
  period_start date not null,
  period_end date not null,
  currency_code char(3) not null,
  category_id bigint null references public.categories(id) on delete set null,
  account_id bigint null references public.accounts(id) on delete set null,
  limit_amount numeric(14,2) not null,
  rollover_enabled boolean not null default false,
  alert_percent numeric(5,2) not null default 80,
  notes text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint budgets_name_not_blank_chk check (btrim(name) <> ''),
  constraint budgets_period_order_chk check (period_end >= period_start),
  constraint budgets_limit_amount_positive_chk check (limit_amount > 0),
  constraint budgets_alert_percent_range_chk check (alert_percent >= 0 and alert_percent <= 100),
  constraint budgets_currency_code_chk check (char_length(btrim(currency_code::text)) = 3)
);

comment on table public.budgets is
  'Presupuestos por periodo. Pueden ser generales, por categoria, por cuenta o por categoria dentro de una cuenta segun category_id y account_id.';

comment on column public.budgets.limit_amount is
  'Monto maximo permitido dentro del periodo.';

comment on column public.budgets.alert_percent is
  'Porcentaje del limite desde el cual el presupuesto entra en alerta.';

create index if not exists budgets_workspace_period_idx
  on public.budgets (workspace_id, period_start, period_end);

create index if not exists budgets_workspace_category_idx
  on public.budgets (workspace_id, category_id, period_start, period_end);

create index if not exists budgets_workspace_account_idx
  on public.budgets (workspace_id, account_id, period_start, period_end);

create index if not exists budgets_workspace_active_idx
  on public.budgets (workspace_id, is_active, period_end desc);

create or replace function public.trg_budgets_normalize_and_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.currency_code := upper(btrim(new.currency_code));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_budgets_normalize_and_touch_updated_at on public.budgets;

create trigger trg_budgets_normalize_and_touch_updated_at
before insert or update on public.budgets
for each row
execute function public.trg_budgets_normalize_and_touch_updated_at();

alter table public.budgets enable row level security;

drop policy if exists budgets_select_workspace_members on public.budgets;
create policy budgets_select_workspace_members
  on public.budgets
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = budgets.workspace_id
        and wm.user_id = auth.uid()
    )
  );

drop policy if exists budgets_insert_workspace_members on public.budgets;
create policy budgets_insert_workspace_members
  on public.budgets
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = budgets.workspace_id
        and wm.user_id = auth.uid()
    )
    and (created_by_user_id is null or created_by_user_id = auth.uid())
    and (updated_by_user_id is null or updated_by_user_id = auth.uid())
  );

drop policy if exists budgets_update_workspace_members on public.budgets;
create policy budgets_update_workspace_members
  on public.budgets
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = budgets.workspace_id
        and wm.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = budgets.workspace_id
        and wm.user_id = auth.uid()
    )
    and (updated_by_user_id is null or updated_by_user_id = auth.uid())
  );

drop policy if exists budgets_delete_workspace_members on public.budgets;
create policy budgets_delete_workspace_members
  on public.budgets
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = budgets.workspace_id
        and wm.user_id = auth.uid()
    )
  );

grant select, insert, update, delete on public.budgets to authenticated;
grant usage, select on sequence public.budgets_id_seq to authenticated;
grant all on public.budgets to service_role;
grant all on sequence public.budgets_id_seq to service_role;

drop view if exists public.v_budget_progress;

create view public.v_budget_progress as
with spend_movements as (
  select
    m.id as movement_id,
    m.workspace_id,
    m.category_id,
    m.source_account_id as account_id,
    m.occurred_at::date as movement_date,
    sa.currency_code as source_currency_code,
    coalesce(m.source_amount, 0)::numeric(14,2) as source_amount
  from public.movements m
  left join public.accounts sa
    on sa.id = m.source_account_id
  where m.status = 'posted'
    and m.movement_type in ('expense', 'subscription_payment', 'obligation_payment')
    and m.source_amount is not null
),
matched_spend as (
  select
    b.id as budget_id,
    sm.movement_id,
    case
      when upper(coalesce(sm.source_currency_code, b.currency_code::text)) = upper(b.currency_code::text)
        then sm.source_amount
      when fx_direct.rate is not null and fx_direct.rate > 0
        then sm.source_amount * fx_direct.rate
      when fx_inverse.rate is not null and fx_inverse.rate > 0
        then sm.source_amount / fx_inverse.rate
      else sm.source_amount
    end::numeric(14,2) as converted_amount
  from public.budgets b
  join spend_movements sm
    on sm.workspace_id = b.workspace_id
   and sm.movement_date between b.period_start and b.period_end
   and (b.category_id is null or sm.category_id = b.category_id)
   and (b.account_id is null or sm.account_id = b.account_id)
  left join public.v_latest_exchange_rates fx_direct
    on upper(fx_direct.from_currency_code) = upper(coalesce(sm.source_currency_code, b.currency_code::text))
   and upper(fx_direct.to_currency_code) = upper(b.currency_code::text)
  left join public.v_latest_exchange_rates fx_inverse
    on upper(fx_inverse.from_currency_code) = upper(b.currency_code::text)
   and upper(fx_inverse.to_currency_code) = upper(coalesce(sm.source_currency_code, b.currency_code::text))
),
budget_rollup as (
  select
    ms.budget_id,
    coalesce(sum(ms.converted_amount), 0)::numeric(14,2) as spent_amount,
    count(*)::integer as movement_count
  from matched_spend ms
  group by ms.budget_id
)
select
  b.id,
  b.workspace_id,
  b.created_by_user_id,
  b.updated_by_user_id,
  b.name,
  b.period_start,
  b.period_end,
  upper(b.currency_code::text) as currency_code,
  b.category_id,
  c.name as category_name,
  b.account_id,
  a.name as account_name,
  case
    when b.category_id is not null and b.account_id is not null then 'category_account'
    when b.category_id is not null then 'category'
    when b.account_id is not null then 'account'
    else 'general'
  end as scope_kind,
  case
    when b.category_id is not null and b.account_id is not null then coalesce(c.name, 'Categoria') || ' en ' || coalesce(a.name, 'cuenta')
    when b.category_id is not null then 'Categoria: ' || coalesce(c.name, 'Sin categoria')
    when b.account_id is not null then 'Cuenta: ' || coalesce(a.name, 'Sin cuenta')
    else 'Gasto total del workspace'
  end as scope_label,
  b.limit_amount::numeric(14,2) as limit_amount,
  coalesce(br.spent_amount, 0)::numeric(14,2) as spent_amount,
  (b.limit_amount - coalesce(br.spent_amount, 0))::numeric(14,2) as remaining_amount,
  case
    when b.limit_amount <= 0 then 0::numeric(7,2)
    else round((coalesce(br.spent_amount, 0) / b.limit_amount) * 100, 2)
  end::numeric(7,2) as used_percent,
  b.alert_percent::numeric(5,2) as alert_percent,
  coalesce(br.movement_count, 0)::integer as movement_count,
  b.rollover_enabled,
  b.notes,
  b.is_active,
  (
    b.is_active
    and coalesce(br.spent_amount, 0) <= b.limit_amount
    and (
      case
        when b.limit_amount <= 0 then 0::numeric
        else round((coalesce(br.spent_amount, 0) / b.limit_amount) * 100, 2)
      end
    ) >= b.alert_percent
  ) as is_near_limit,
  (b.is_active and coalesce(br.spent_amount, 0) > b.limit_amount) as is_over_limit,
  b.created_at,
  b.updated_at
from public.budgets b
left join public.categories c
  on c.id = b.category_id
left join public.accounts a
  on a.id = b.account_id
left join budget_rollup br
  on br.budget_id = b.id;

comment on view public.v_budget_progress is
  'Calcula gasto ejecutado, saldo remanente, porcentaje usado y alertas de cada presupuesto activo o historico.';

grant select on public.v_budget_progress to authenticated;
grant select on public.v_budget_progress to service_role;
