-- Roles de negocio para contrapartes y vista resumen para dashboards de contactos.

do $$
begin
  create type public.counterparty_role_type as enum (
    'client',
    'supplier',
    'lender',
    'borrower',
    'bank',
    'service_provider',
    'other'
  );
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.counterparty_roles (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  counterparty_id bigint not null references public.counterparties(id) on delete cascade,
  role_type public.counterparty_role_type not null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint counterparty_roles_unique_role_per_counterparty unique (counterparty_id, role_type)
);

comment on table public.counterparty_roles is
  'Roles de negocio de una contraparte dentro del workspace. Permite tratarla como cliente, proveedor, prestamista, deudor, banco, etc.';

comment on column public.counterparty_roles.role_type is
  'Rol funcional de la contraparte respecto al usuario o workspace.';

comment on column public.counterparty_roles.notes is
  'Observaciones internas del rol asignado.';

create index if not exists counterparty_roles_workspace_idx
  on public.counterparty_roles (workspace_id, role_type, counterparty_id);

create index if not exists counterparty_roles_counterparty_idx
  on public.counterparty_roles (counterparty_id, role_type);

create or replace function public.trg_counterparty_roles_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_counterparty_roles_touch_updated_at on public.counterparty_roles;

create trigger trg_counterparty_roles_touch_updated_at
before update on public.counterparty_roles
for each row
execute function public.trg_counterparty_roles_touch_updated_at();

drop view if exists public.v_counterparty_summary;

create view public.v_counterparty_summary as
with role_rollup as (
  select
    cr.workspace_id,
    cr.counterparty_id,
    array_agg(cr.role_type::text order by cr.role_type::text) as roles
  from public.counterparty_roles cr
  group by cr.workspace_id, cr.counterparty_id
),
obligation_rollup as (
  select
    vos.workspace_id,
    vos.counterparty_id,
    count(*) filter (where vos.direction = 'receivable')::integer as receivable_count,
    coalesce(
      sum(case when vos.direction = 'receivable' then vos.principal_current_amount else 0 end),
      0
    )::numeric(14,2) as receivable_principal_total,
    coalesce(
      sum(case when vos.direction = 'receivable' then vos.pending_amount else 0 end),
      0
    )::numeric(14,2) as receivable_pending_total,
    count(*) filter (where vos.direction = 'payable')::integer as payable_count,
    coalesce(
      sum(case when vos.direction = 'payable' then vos.principal_current_amount else 0 end),
      0
    )::numeric(14,2) as payable_principal_total,
    coalesce(
      sum(case when vos.direction = 'payable' then vos.pending_amount else 0 end),
      0
    )::numeric(14,2) as payable_pending_total,
    max(coalesce(vos.last_event_date::timestamptz, vos.updated_at)) as last_obligation_activity_at
  from public.v_obligation_summary vos
  where vos.counterparty_id is not null
  group by vos.workspace_id, vos.counterparty_id
),
movement_rollup as (
  select
    m.workspace_id,
    m.counterparty_id,
    count(*) filter (where m.status = 'posted')::integer as movement_count,
    coalesce(
      sum(
        case
          when m.status = 'posted' and m.movement_type in ('income', 'refund')
            then coalesce(m.destination_amount, m.source_amount, 0)
          else 0
        end
      ),
      0
    )::numeric(14,2) as inflow_total,
    coalesce(
      sum(
        case
          when m.status = 'posted'
           and m.movement_type in ('expense', 'subscription_payment', 'obligation_payment')
            then coalesce(m.source_amount, m.destination_amount, 0)
          else 0
        end
      ),
      0
    )::numeric(14,2) as outflow_total,
    max(m.occurred_at) filter (where m.status = 'posted') as last_movement_at
  from public.movements m
  where m.counterparty_id is not null
  group by m.workspace_id, m.counterparty_id
)
select
  cp.workspace_id,
  cp.id as counterparty_id,
  cp.name,
  cp.type,
  cp.phone,
  cp.email,
  cp.document_number,
  cp.notes,
  cp.is_archived,
  coalesce(rr.roles, array[]::text[]) as roles,
  coalesce(orw.receivable_count, 0)::integer as receivable_count,
  coalesce(orw.receivable_principal_total, 0)::numeric(14,2) as receivable_principal_total,
  coalesce(orw.receivable_pending_total, 0)::numeric(14,2) as receivable_pending_total,
  coalesce(orw.payable_count, 0)::integer as payable_count,
  coalesce(orw.payable_principal_total, 0)::numeric(14,2) as payable_principal_total,
  coalesce(orw.payable_pending_total, 0)::numeric(14,2) as payable_pending_total,
  (
    coalesce(orw.receivable_pending_total, 0) - coalesce(orw.payable_pending_total, 0)
  )::numeric(14,2) as net_pending_amount,
  coalesce(mrw.movement_count, 0)::integer as movement_count,
  coalesce(mrw.inflow_total, 0)::numeric(14,2) as inflow_total,
  coalesce(mrw.outflow_total, 0)::numeric(14,2) as outflow_total,
  (
    coalesce(mrw.inflow_total, 0) - coalesce(mrw.outflow_total, 0)
  )::numeric(14,2) as net_flow_amount,
  greatest(
    coalesce(mrw.last_movement_at, '-infinity'::timestamptz),
    coalesce(orw.last_obligation_activity_at, '-infinity'::timestamptz),
    cp.updated_at
  ) as last_activity_at,
  cp.created_at,
  cp.updated_at
from public.counterparties cp
left join role_rollup rr
  on rr.workspace_id = cp.workspace_id
 and rr.counterparty_id = cp.id
left join obligation_rollup orw
  on orw.workspace_id = cp.workspace_id
 and orw.counterparty_id = cp.id
left join movement_rollup mrw
  on mrw.workspace_id = cp.workspace_id
 and mrw.counterparty_id = cp.id;

comment on view public.v_counterparty_summary is
  'Resumen por contraparte para dashboards: roles, exposicion por cobrar, exposicion por pagar, flujo historico y ultima actividad.';
