-- Meta de ahorro mensual por usuario y workspace (dashboard Pro).
-- Ejecutar en Supabase SQL Editor o con tu pipeline de migraciones.

create table if not exists public.workspace_financial_goals (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  monthly_savings_target numeric(14,2) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workspace_financial_goals_workspace_user_uniq unique (workspace_id, user_id),
  constraint workspace_financial_goals_target_positive_chk check (monthly_savings_target > 0)
);

comment on table public.workspace_financial_goals is
  'Meta de ahorro neto mensual definida por el usuario en el dashboard (Pro). Una fila por par workspace + usuario.';

create index if not exists workspace_financial_goals_workspace_user_idx
  on public.workspace_financial_goals (workspace_id, user_id);

create or replace function public.trg_workspace_financial_goals_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_workspace_financial_goals_touch_updated_at on public.workspace_financial_goals;

create trigger trg_workspace_financial_goals_touch_updated_at
before update on public.workspace_financial_goals
for each row
execute function public.trg_workspace_financial_goals_touch_updated_at();

alter table public.workspace_financial_goals enable row level security;

drop policy if exists workspace_financial_goals_select_own on public.workspace_financial_goals;
create policy workspace_financial_goals_select_own
  on public.workspace_financial_goals
  for select
  to authenticated
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = workspace_financial_goals.workspace_id
        and wm.user_id = auth.uid()
    )
  );

drop policy if exists workspace_financial_goals_insert_own on public.workspace_financial_goals;
create policy workspace_financial_goals_insert_own
  on public.workspace_financial_goals
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = workspace_financial_goals.workspace_id
        and wm.user_id = auth.uid()
    )
  );

drop policy if exists workspace_financial_goals_update_own on public.workspace_financial_goals;
create policy workspace_financial_goals_update_own
  on public.workspace_financial_goals
  for update
  to authenticated
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = workspace_financial_goals.workspace_id
        and wm.user_id = auth.uid()
    )
  )
  with check (
    user_id = auth.uid()
    and exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = workspace_financial_goals.workspace_id
        and wm.user_id = auth.uid()
    )
  );

drop policy if exists workspace_financial_goals_delete_own on public.workspace_financial_goals;
create policy workspace_financial_goals_delete_own
  on public.workspace_financial_goals
  for delete
  to authenticated
  using (
    user_id = auth.uid()
    and exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = workspace_financial_goals.workspace_id
        and wm.user_id = auth.uid()
    )
  );

grant select, insert, update, delete on public.workspace_financial_goals to authenticated;
grant usage, select on sequence public.workspace_financial_goals_id_seq to authenticated;
grant all on public.workspace_financial_goals to service_role;
grant all on sequence public.workspace_financial_goals_id_seq to service_role;
