create table if not exists public.workspace_invitations (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  invited_by_user_id uuid not null references auth.users(id) on delete restrict,
  invited_user_id uuid not null references auth.users(id) on delete restrict,
  invited_email text not null,
  invited_display_name text null,
  invited_by_display_name text null,
  role public.workspace_role not null default 'member',
  status public.workspace_invitation_status not null default 'pending',
  token uuid not null default gen_random_uuid(),
  note text null,
  accepted_at timestamptz null,
  responded_at timestamptz null,
  last_sent_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workspace_invitations_invited_email_not_blank_chk check (btrim(invited_email) <> ''),
  constraint workspace_invitations_metadata_object_chk check (jsonb_typeof(metadata) = 'object')
);

alter table public.workspace_invitations
  add column if not exists invited_user_id uuid null references auth.users(id) on delete restrict,
  add column if not exists invited_display_name text null,
  add column if not exists invited_by_display_name text null,
  add column if not exists token uuid not null default gen_random_uuid(),
  add column if not exists accepted_at timestamptz null,
  add column if not exists responded_at timestamptz null,
  add column if not exists last_sent_at timestamptz null,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

comment on table public.workspace_invitations is
  'Invitaciones para sumar miembros a workspaces compartidos de DarkMoney.';

comment on column public.workspace_invitations.invited_email is
  'Correo del usuario invitado, normalizado en minusculas.';

comment on column public.workspace_invitations.invited_user_id is
  'Usuario real de DarkMoney asociado al correo invitado.';

comment on column public.workspace_invitations.role is
  'Rol que recibira el usuario al aceptar la invitacion.';

comment on column public.workspace_invitations.token is
  'Token unico incluido en el enlace del correo para revisar y aceptar la invitacion.';

comment on column public.workspace_invitations.note is
  'Mensaje opcional incluido por quien envia la invitacion.';

comment on column public.workspace_invitations.metadata is
  'JSON de apoyo para auditoria o contexto adicional de la invitacion.';

create unique index if not exists workspace_invitations_token_uidx
  on public.workspace_invitations (token);

create unique index if not exists workspace_invitations_active_workspace_user_uidx
  on public.workspace_invitations (workspace_id, invited_user_id)
  where status in ('pending', 'accepted');

create index if not exists workspace_invitations_workspace_status_idx
  on public.workspace_invitations (workspace_id, status, updated_at desc);

create index if not exists workspace_invitations_invited_user_status_idx
  on public.workspace_invitations (invited_user_id, status, updated_at desc);

create or replace function public.trg_workspace_invitations_normalize_and_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.invited_email := lower(btrim(new.invited_email));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_workspace_invitations_normalize_and_touch_updated_at on public.workspace_invitations;

create trigger trg_workspace_invitations_normalize_and_touch_updated_at
before insert or update on public.workspace_invitations
for each row
execute function public.trg_workspace_invitations_normalize_and_touch_updated_at();

create or replace function public.find_darkmoney_user_by_email(lookup_email text)
returns table (
  user_id uuid,
  email text,
  full_name text
)
language sql
security definer
set search_path = public, auth
as $$
  select
    u.id as user_id,
    lower(u.email) as email,
    coalesce(nullif(btrim(p.full_name), ''), split_part(u.email, '@', 1)) as full_name
  from auth.users u
  left join public.profiles p
    on p.id = u.id
  where lower(u.email) = lower(btrim(lookup_email))
  limit 1
$$;

comment on function public.find_darkmoney_user_by_email(text) is
  'Busca un usuario real de DarkMoney por email para invitaciones colaborativas y registros compartidos.';

revoke all on function public.find_darkmoney_user_by_email(text) from public;
grant execute on function public.find_darkmoney_user_by_email(text) to service_role;

create or replace function public.find_darkmoney_users_by_ids(lookup_user_ids uuid[])
returns table (
  user_id uuid,
  email text,
  full_name text
)
language sql
security definer
set search_path = public, auth
as $$
  select
    u.id as user_id,
    lower(u.email) as email,
    coalesce(nullif(btrim(p.full_name), ''), split_part(u.email, '@', 1)) as full_name
  from auth.users u
  left join public.profiles p
    on p.id = u.id
  where u.id = any(coalesce(lookup_user_ids, array[]::uuid[]))
$$;

comment on function public.find_darkmoney_users_by_ids(uuid[]) is
  'Devuelve usuarios reales de DarkMoney por lista de ids para flujos colaborativos.';

revoke all on function public.find_darkmoney_users_by_ids(uuid[]) from public;
grant execute on function public.find_darkmoney_users_by_ids(uuid[]) to service_role;

alter table public.workspace_invitations enable row level security;

drop policy if exists workspace_invitations_select_workspace_members on public.workspace_invitations;
create policy workspace_invitations_select_workspace_members
  on public.workspace_invitations
  for select
  to authenticated
  using (
    invited_user_id = auth.uid()
    or exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = workspace_invitations.workspace_id
        and wm.user_id = auth.uid()
    )
  );

drop policy if exists workspace_invitations_service_role_all on public.workspace_invitations;
create policy workspace_invitations_service_role_all
  on public.workspace_invitations
  for all
  to service_role
  using (true)
  with check (true);

grant select on public.workspace_invitations to authenticated;
grant all on public.workspace_invitations to service_role;
grant usage, select on sequence public.workspace_invitations_id_seq to service_role;
