-- =============================================================================
-- Ingresos fijos recurrentes (salario, renta cobrada, pension, etc.)
-- Contraparte semantica de la tabla subscriptions (gastos fijos).
-- =============================================================================

create table if not exists public.recurring_income (
  id                   bigint generated by default as identity primary key,
  workspace_id         bigint not null references public.workspaces(id) on delete cascade,
  created_by_user_id   uuid   null,
  updated_by_user_id   uuid   null,

  -- Descripcion
  name                 text   not null,
  payer_party_id       bigint null references public.counterparties(id) on delete set null,
  account_id           bigint null references public.accounts(id) on delete set null,
  category_id          bigint null references public.categories(id) on delete set null,

  -- Monto y moneda
  currency_code        char(3) not null,
  amount               numeric(14,2) not null,

  -- Recurrencia (mismos valores que subscriptions)
  frequency            text   not null default 'monthly',
  interval_count       int    not null default 1,
  day_of_month         int    null,   -- 1-31
  day_of_week          int    null,   -- 0=domingo … 6=sabado

  -- Ciclo de vida
  start_date           date   not null,
  next_expected_date   date   not null,   -- equivalente a next_due_date en subscriptions
  end_date             date   null,
  status               text   not null default 'active',

  -- Alertas
  remind_days_before   int    not null default 2,

  -- Anotaciones
  description          text   null,
  notes                text   null,

  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),

  -- Constraints de integridad
  constraint recurring_income_name_not_blank_chk
    check (btrim(name) <> ''),
  constraint recurring_income_amount_positive_chk
    check (amount > 0),
  constraint recurring_income_interval_count_positive_chk
    check (interval_count >= 1),
  constraint recurring_income_frequency_chk
    check (frequency in ('daily', 'weekly', 'monthly', 'quarterly', 'yearly', 'custom')),
  constraint recurring_income_status_chk
    check (status in ('active', 'paused', 'cancelled')),
  constraint recurring_income_currency_code_chk
    check (char_length(btrim(currency_code::text)) = 3),
  constraint recurring_income_remind_days_chk
    check (remind_days_before >= 0),
  constraint recurring_income_day_of_month_chk
    check (day_of_month is null or (day_of_month >= 1 and day_of_month <= 31)),
  constraint recurring_income_day_of_week_chk
    check (day_of_week is null or (day_of_week >= 0 and day_of_week <= 6)),
  constraint recurring_income_dates_order_chk
    check (end_date is null or end_date >= start_date)
);

comment on table public.recurring_income is
  'Ingresos fijos recurrentes (salario, renta cobrada, pension, etc.). Contraparte semantica de subscriptions.';
comment on column public.recurring_income.payer_party_id is
  'Contraparte que emite el pago (empleador, inquilino, cliente fijo, etc.).';
comment on column public.recurring_income.next_expected_date is
  'Proxima fecha esperada de recepcion. Equivalente semantico de next_due_date en subscriptions.';
comment on column public.recurring_income.remind_days_before is
  'Dias despues de next_expected_date sin ingreso para activar notificacion.';

-- Indices
create index if not exists recurring_income_workspace_status_idx
  on public.recurring_income (workspace_id, status);

create index if not exists recurring_income_workspace_next_expected_idx
  on public.recurring_income (workspace_id, next_expected_date);

-- =============================================================================
-- Trigger: normalizar currency_code y actualizar updated_at
-- =============================================================================

create or replace function public.trg_recurring_income_normalize_and_touch()
returns trigger
language plpgsql
as $$
begin
  new.currency_code := upper(btrim(new.currency_code));
  new.updated_at    := now();
  return new;
end;
$$;

drop trigger if exists trg_recurring_income_normalize_and_touch on public.recurring_income;
create trigger trg_recurring_income_normalize_and_touch
  before insert or update on public.recurring_income
  for each row
  execute function public.trg_recurring_income_normalize_and_touch();

-- =============================================================================
-- Row Level Security
-- =============================================================================

alter table public.recurring_income enable row level security;

-- SELECT
drop policy if exists recurring_income_select_workspace_members on public.recurring_income;
create policy recurring_income_select_workspace_members
  on public.recurring_income for select to authenticated
  using (
    exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = recurring_income.workspace_id
        and wm.user_id = auth.uid()
    )
  );

-- INSERT
drop policy if exists recurring_income_insert_workspace_members on public.recurring_income;
create policy recurring_income_insert_workspace_members
  on public.recurring_income for insert to authenticated
  with check (
    exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = recurring_income.workspace_id
        and wm.user_id = auth.uid()
    )
    and (created_by_user_id is null or created_by_user_id = auth.uid())
    and (updated_by_user_id is null or updated_by_user_id = auth.uid())
  );

-- UPDATE
drop policy if exists recurring_income_update_workspace_members on public.recurring_income;
create policy recurring_income_update_workspace_members
  on public.recurring_income for update to authenticated
  using (
    exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = recurring_income.workspace_id
        and wm.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = recurring_income.workspace_id
        and wm.user_id = auth.uid()
    )
    and (updated_by_user_id is null or updated_by_user_id = auth.uid())
  );

-- DELETE
drop policy if exists recurring_income_delete_workspace_members on public.recurring_income;
create policy recurring_income_delete_workspace_members
  on public.recurring_income for delete to authenticated
  using (
    exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id = recurring_income.workspace_id
        and wm.user_id = auth.uid()
    )
  );

-- =============================================================================
-- Grants
-- =============================================================================

grant select, insert, update, delete on public.recurring_income to authenticated;
grant usage, select on sequence public.recurring_income_id_seq to authenticated;
grant all on public.recurring_income to service_role;
grant all on sequence public.recurring_income_id_seq to service_role;
