create table if not exists public.exchange_rates (
  id bigint generated by default as identity primary key,
  from_currency_code text not null,
  to_currency_code text not null,
  rate numeric(18,8) not null,
  effective_at timestamptz not null default now(),
  source text null,
  notes text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint exchange_rates_currency_code_length_chk check (
    char_length(btrim(from_currency_code)) = 3
    and char_length(btrim(to_currency_code)) = 3
  ),
  constraint exchange_rates_currency_pair_chk check (
    upper(btrim(from_currency_code)) <> upper(btrim(to_currency_code))
  ),
  constraint exchange_rates_rate_positive_chk check (rate > 0)
);

comment on table public.exchange_rates is
  'Tipos de cambio historicos. La regla es: 1 from_currency_code = rate to_currency_code.';

comment on column public.exchange_rates.rate is
  'Cuantas unidades de to_currency_code equivalen a 1 unidad de from_currency_code.';

create unique index if not exists exchange_rates_pair_effective_at_uidx
  on public.exchange_rates (
    upper(btrim(from_currency_code)),
    upper(btrim(to_currency_code)),
    effective_at
  );

create index if not exists exchange_rates_lookup_idx
  on public.exchange_rates (
    upper(btrim(from_currency_code)),
    upper(btrim(to_currency_code)),
    effective_at desc
  );

create or replace function public.trg_exchange_rates_normalize()
returns trigger
language plpgsql
as $$
begin
  new.from_currency_code := upper(btrim(new.from_currency_code));
  new.to_currency_code := upper(btrim(new.to_currency_code));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_exchange_rates_normalize on public.exchange_rates;

create trigger trg_exchange_rates_normalize
before insert or update on public.exchange_rates
for each row
execute function public.trg_exchange_rates_normalize();

alter table public.exchange_rates enable row level security;

drop policy if exists exchange_rates_select_authenticated on public.exchange_rates;
create policy exchange_rates_select_authenticated
  on public.exchange_rates
  for select
  to authenticated
  using (true);

drop policy if exists exchange_rates_manage_service_role on public.exchange_rates;
create policy exchange_rates_manage_service_role
  on public.exchange_rates
  for all
  to service_role
  using (true)
  with check (true);

grant select on public.exchange_rates to authenticated;
grant all on public.exchange_rates to service_role;

create or replace view public.v_latest_exchange_rates as
select distinct on (
  upper(btrim(from_currency_code)),
  upper(btrim(to_currency_code))
)
  id,
  upper(btrim(from_currency_code)) as from_currency_code,
  upper(btrim(to_currency_code)) as to_currency_code,
  rate,
  effective_at,
  source,
  notes,
  created_at,
  updated_at
from public.exchange_rates
order by
  upper(btrim(from_currency_code)),
  upper(btrim(to_currency_code)),
  effective_at desc,
  id desc;

