create table if not exists public.obligation_shares (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  obligation_id bigint not null references public.obligations(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete restrict,
  invited_by_user_id uuid not null references auth.users(id) on delete restrict,
  invited_user_id uuid not null references auth.users(id) on delete restrict,
  owner_display_name text null,
  invited_display_name text null,
  invited_email text not null,
  status text not null default 'pending',
  token uuid not null default gen_random_uuid(),
  message text null,
  accepted_at timestamptz null,
  responded_at timestamptz null,
  last_sent_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint obligation_shares_status_chk check (status in ('pending', 'accepted', 'declined', 'revoked')),
  constraint obligation_shares_invited_email_not_blank_chk check (btrim(invited_email) <> ''),
  constraint obligation_shares_metadata_object_chk check (jsonb_typeof(metadata) = 'object')
);

comment on table public.obligation_shares is
  'Invitaciones y acceso compartido de creditos o deudas con otros usuarios de DarkMoney.';

comment on column public.obligation_shares.invited_email is
  'Correo del usuario invitado, normalizado en minusculas para auditoria y correos.';

comment on column public.obligation_shares.token is
  'Token unico usado en el enlace de correo para revisar y aceptar el acceso compartido.';

comment on column public.obligation_shares.status is
  'Estado de la invitacion compartida: pending, accepted, declined o revoked.';

create unique index if not exists obligation_shares_token_uidx
  on public.obligation_shares (token);

create unique index if not exists obligation_shares_active_obligation_uidx
  on public.obligation_shares (obligation_id)
  where status in ('pending', 'accepted');

create index if not exists obligation_shares_workspace_status_idx
  on public.obligation_shares (workspace_id, status, updated_at desc);

create index if not exists obligation_shares_invited_user_status_idx
  on public.obligation_shares (invited_user_id, status, updated_at desc);

create or replace function public.trg_obligation_shares_normalize_and_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.invited_email := lower(btrim(new.invited_email));
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_obligation_shares_normalize_and_touch_updated_at on public.obligation_shares;

create trigger trg_obligation_shares_normalize_and_touch_updated_at
before insert or update on public.obligation_shares
for each row
execute function public.trg_obligation_shares_normalize_and_touch_updated_at();

create or replace function public.find_darkmoney_user_by_email(lookup_email text)
returns table (
  user_id uuid,
  email text,
  full_name text
)
language sql
security definer
set search_path = public, auth
as $$
  select
    u.id as user_id,
    lower(u.email) as email,
    coalesce(nullif(btrim(p.full_name), ''), split_part(u.email, '@', 1)) as full_name
  from auth.users u
  left join public.profiles p
    on p.id = u.id
  where lower(u.email) = lower(btrim(lookup_email))
  limit 1
$$;

comment on function public.find_darkmoney_user_by_email(text) is
  'Busca un usuario real de DarkMoney por email para validar invitaciones y shares de obligaciones.';

revoke all on function public.find_darkmoney_user_by_email(text) from public;
grant execute on function public.find_darkmoney_user_by_email(text) to service_role;

alter table public.obligation_shares enable row level security;

drop policy if exists obligation_shares_select_workspace_members on public.obligation_shares;
create policy obligation_shares_select_workspace_members
  on public.obligation_shares
  for select
  to authenticated
  using (
    invited_user_id = auth.uid()
    or exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = obligation_shares.workspace_id
        and wm.user_id = auth.uid()
    )
  );

drop policy if exists obligation_shares_service_role_all on public.obligation_shares;
create policy obligation_shares_service_role_all
  on public.obligation_shares
  for all
  to service_role
  using (true)
  with check (true);

grant select on public.obligation_shares to authenticated;
grant all on public.obligation_shares to service_role;
grant usage, select on sequence public.obligation_shares_id_seq to service_role;
