-- Extiende creditos y deudas para soportar historial de cambios de principal,
-- auditoria y una vista resumen mas completa.

alter type public.obligation_event_type add value if not exists 'principal_increase';
alter type public.obligation_event_type add value if not exists 'principal_decrease';

alter table public.obligation_events
  add column if not exists reason text null,
  add column if not exists created_by_user_id uuid null,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

comment on column public.obligation_events.reason is
  'Motivo funcional del cambio o evento. Ejemplo: Se presto 500 adicionales.';

comment on column public.obligation_events.created_by_user_id is
  'Usuario que registro el evento en la aplicacion.';

comment on column public.obligation_events.metadata is
  'JSON opcional para datos adicionales del evento.';

create index if not exists obligation_events_obligation_date_idx
  on public.obligation_events (obligation_id, event_date desc, id desc);

create index if not exists obligation_events_type_date_idx
  on public.obligation_events (event_type, event_date desc, id desc);

create table if not exists public.obligation_change_history (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  obligation_id bigint not null references public.obligations(id) on delete cascade,
  change_type text not null,
  reason text null,
  changed_by_user_id uuid null,
  before_data jsonb not null default '{}'::jsonb,
  after_data jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint obligation_change_history_change_type_not_blank_chk check (btrim(change_type) <> ''),
  constraint obligation_change_history_before_data_object_chk check (jsonb_typeof(before_data) = 'object'),
  constraint obligation_change_history_after_data_object_chk check (jsonb_typeof(after_data) = 'object'),
  constraint obligation_change_history_metadata_object_chk check (jsonb_typeof(metadata) = 'object')
);

comment on table public.obligation_change_history is
  'Auditoria de cambios estructurales en creditos y deudas.';

comment on column public.obligation_change_history.change_type is
  'Tipo de cambio. Ejemplos: principal_increase, principal_decrease, conditions_updated, status_updated.';

comment on column public.obligation_change_history.reason is
  'Motivo funcional del cambio.';

comment on column public.obligation_change_history.changed_by_user_id is
  'Usuario que realizo el cambio.';

comment on column public.obligation_change_history.before_data is
  'Snapshot del registro antes del cambio.';

comment on column public.obligation_change_history.after_data is
  'Snapshot del registro despues del cambio.';

comment on column public.obligation_change_history.metadata is
  'JSON opcional con contexto adicional del cambio.';

create index if not exists obligation_change_history_obligation_created_idx
  on public.obligation_change_history (obligation_id, created_at desc, id desc);

create index if not exists obligation_change_history_workspace_created_idx
  on public.obligation_change_history (workspace_id, created_at desc, id desc);

drop view if exists public.v_counterparty_summary;
drop view if exists public.v_obligation_summary;

create view public.v_obligation_summary as
with event_rollup as (
  select
    oe.obligation_id,
    coalesce(sum(case when oe.event_type::text = 'principal_increase' then oe.amount else 0 end), 0)::numeric(14,2) as principal_increase_total,
    coalesce(sum(case when oe.event_type::text = 'principal_decrease' then oe.amount else 0 end), 0)::numeric(14,2) as principal_decrease_total,
    coalesce(sum(case when oe.event_type::text = 'payment' then oe.amount else 0 end), 0)::numeric(14,2) as payment_total,
    coalesce(sum(case when oe.event_type::text = 'interest' then oe.amount else 0 end), 0)::numeric(14,2) as interest_total,
    coalesce(sum(case when oe.event_type::text = 'fee' then oe.amount else 0 end), 0)::numeric(14,2) as fee_total,
    coalesce(sum(case when oe.event_type::text = 'discount' then oe.amount else 0 end), 0)::numeric(14,2) as discount_total,
    coalesce(sum(case when oe.event_type::text = 'writeoff' then oe.amount else 0 end), 0)::numeric(14,2) as writeoff_total,
    coalesce(sum(case when oe.event_type::text = 'adjustment' then oe.amount else 0 end), 0)::numeric(14,2) as adjustment_total,
    count(*) filter (where oe.event_type::text = 'payment')::integer as payment_count,
    max(oe.event_date) filter (where oe.event_type::text = 'payment') as last_payment_date,
    max(oe.event_date) as last_event_date
  from public.obligation_events oe
  group by oe.obligation_id
),
summary_base as (
  select
    o.id,
    o.workspace_id,
    o.direction,
    o.origin_type,
    o.status,
    o.title,
    o.counterparty_id,
    o.settlement_account_id,
    o.currency_code,
    o.principal_amount::numeric(14,2) as principal_initial_amount,
    coalesce(er.principal_increase_total, 0)::numeric(14,2) as principal_increase_total,
    coalesce(er.principal_decrease_total, 0)::numeric(14,2) as principal_decrease_total,
    (
      o.principal_amount
      + coalesce(er.principal_increase_total, 0)
      - coalesce(er.principal_decrease_total, 0)
    )::numeric(14,2) as principal_current_amount,
    coalesce(er.interest_total, 0)::numeric(14,2) as interest_total,
    coalesce(er.fee_total, 0)::numeric(14,2) as fee_total,
    coalesce(er.adjustment_total, 0)::numeric(14,2) as adjustment_total,
    coalesce(er.discount_total, 0)::numeric(14,2) as discount_total,
    coalesce(er.writeoff_total, 0)::numeric(14,2) as writeoff_total,
    coalesce(er.payment_total, 0)::numeric(14,2) as payment_total,
    greatest(
      0::numeric,
      (
        o.principal_amount
        + coalesce(er.principal_increase_total, 0)
        - coalesce(er.principal_decrease_total, 0)
        + coalesce(er.interest_total, 0)
        + coalesce(er.fee_total, 0)
        + coalesce(er.adjustment_total, 0)
        - coalesce(er.discount_total, 0)
        - coalesce(er.writeoff_total, 0)
        - coalesce(er.payment_total, 0)
      )
    )::numeric(14,2) as pending_amount,
    o.start_date,
    o.due_date,
    o.installment_amount,
    o.installment_count,
    o.interest_rate,
    o.description,
    o.notes,
    coalesce(er.payment_count, 0)::integer as payment_count,
    er.last_payment_date,
    er.last_event_date,
    o.created_at,
    o.updated_at
  from public.obligations o
  left join event_rollup er on er.obligation_id = o.id
)
select
  sb.*,
  case
    when (
      sb.principal_current_amount
      + sb.interest_total
      + sb.fee_total
      + sb.adjustment_total
      - sb.discount_total
      - sb.writeoff_total
    ) <= 0 then 0::numeric
    else least(
      100::numeric,
      round(
        (
          (
            (
              sb.principal_current_amount
              + sb.interest_total
              + sb.fee_total
              + sb.adjustment_total
              - sb.discount_total
              - sb.writeoff_total
            )
            - sb.pending_amount
          )
          / nullif(
              sb.principal_current_amount
              + sb.interest_total
              + sb.fee_total
              + sb.adjustment_total
              - sb.discount_total
              - sb.writeoff_total,
              0::numeric
            )
        ) * 100,
        0
      )
    )
  end as progress_percent
from summary_base sb;

comment on view public.v_obligation_summary is
  'Resumen de creditos y deudas con principal inicial, aumentos, reducciones, pagos, extras, saldo pendiente y porcentaje de avance.';

do $$
begin
  if to_regclass('public.counterparty_roles') is not null then
    execute $counterparty_view$
      create view public.v_counterparty_summary as
      with role_rollup as (
        select
          cr.workspace_id,
          cr.counterparty_id,
          array_agg(cr.role_type::text order by cr.role_type::text) as roles
        from public.counterparty_roles cr
        group by cr.workspace_id, cr.counterparty_id
      ),
      obligation_rollup as (
        select
          vos.workspace_id,
          vos.counterparty_id,
          count(*) filter (where vos.direction = 'receivable')::integer as receivable_count,
          coalesce(
            sum(case when vos.direction = 'receivable' then vos.principal_current_amount else 0 end),
            0
          )::numeric(14,2) as receivable_principal_total,
          coalesce(
            sum(case when vos.direction = 'receivable' then vos.pending_amount else 0 end),
            0
          )::numeric(14,2) as receivable_pending_total,
          count(*) filter (where vos.direction = 'payable')::integer as payable_count,
          coalesce(
            sum(case when vos.direction = 'payable' then vos.principal_current_amount else 0 end),
            0
          )::numeric(14,2) as payable_principal_total,
          coalesce(
            sum(case when vos.direction = 'payable' then vos.pending_amount else 0 end),
            0
          )::numeric(14,2) as payable_pending_total,
          max(coalesce(vos.last_event_date::timestamptz, vos.updated_at)) as last_obligation_activity_at
        from public.v_obligation_summary vos
        where vos.counterparty_id is not null
        group by vos.workspace_id, vos.counterparty_id
      ),
      movement_rollup as (
        select
          m.workspace_id,
          m.counterparty_id,
          count(*) filter (where m.status = 'posted')::integer as movement_count,
          coalesce(
            sum(
              case
                when m.status = 'posted' and m.movement_type in ('income', 'refund')
                  then coalesce(m.destination_amount, m.source_amount, 0)
                else 0
              end
            ),
            0
          )::numeric(14,2) as inflow_total,
          coalesce(
            sum(
              case
                when m.status = 'posted'
                 and m.movement_type in ('expense', 'subscription_payment', 'obligation_payment')
                  then coalesce(m.source_amount, m.destination_amount, 0)
                else 0
              end
            ),
            0
          )::numeric(14,2) as outflow_total,
          max(m.occurred_at) filter (where m.status = 'posted') as last_movement_at
        from public.movements m
        where m.counterparty_id is not null
        group by m.workspace_id, m.counterparty_id
      )
      select
        cp.workspace_id,
        cp.id as counterparty_id,
        cp.name,
        cp.type,
        cp.phone,
        cp.email,
        cp.document_number,
        cp.notes,
        cp.is_archived,
        coalesce(rr.roles, array[]::text[]) as roles,
        coalesce(orw.receivable_count, 0)::integer as receivable_count,
        coalesce(orw.receivable_principal_total, 0)::numeric(14,2) as receivable_principal_total,
        coalesce(orw.receivable_pending_total, 0)::numeric(14,2) as receivable_pending_total,
        coalesce(orw.payable_count, 0)::integer as payable_count,
        coalesce(orw.payable_principal_total, 0)::numeric(14,2) as payable_principal_total,
        coalesce(orw.payable_pending_total, 0)::numeric(14,2) as payable_pending_total,
        (
          coalesce(orw.receivable_pending_total, 0) - coalesce(orw.payable_pending_total, 0)
        )::numeric(14,2) as net_pending_amount,
        coalesce(mrw.movement_count, 0)::integer as movement_count,
        coalesce(mrw.inflow_total, 0)::numeric(14,2) as inflow_total,
        coalesce(mrw.outflow_total, 0)::numeric(14,2) as outflow_total,
        (
          coalesce(mrw.inflow_total, 0) - coalesce(mrw.outflow_total, 0)
        )::numeric(14,2) as net_flow_amount,
        greatest(
          coalesce(mrw.last_movement_at, '-infinity'::timestamptz),
          coalesce(orw.last_obligation_activity_at, '-infinity'::timestamptz),
          cp.updated_at
        ) as last_activity_at,
        cp.created_at,
        cp.updated_at
      from public.counterparties cp
      left join role_rollup rr
        on rr.workspace_id = cp.workspace_id
       and rr.counterparty_id = cp.id
      left join obligation_rollup orw
        on orw.workspace_id = cp.workspace_id
       and orw.counterparty_id = cp.id
      left join movement_rollup mrw
        on mrw.workspace_id = cp.workspace_id
       and mrw.counterparty_id = cp.id
    $counterparty_view$;

    execute $counterparty_comment$
      comment on view public.v_counterparty_summary is
        'Resumen por contraparte para dashboards: roles, exposicion por cobrar, exposicion por pagar, flujo historico y ultima actividad.'
    $counterparty_comment$;
  end if;
end
$$;
